### ISSUE TITLE
Revision needed

### ISSUE THREAD

**Issue by Benomrans** [agmmnn/pushkin-downloader#1]
Hello,
Sorry to report that the app for some reason is no longer working on both sites, It was working perfectly.
Would you please check it up.
Thank you so much.

**Comment by agmmnn** [comment]
Hey @Benomrans, I implemented in Dezoomify, https://github.com/lovasoa/dezoomify/pull/704 you can use: https://dezoomify.ophir.dev/

This is actually still functional, but I turned down the server machine settings, because it uses node in the background and consumes server resources, while dezoomify uses the canvas of the browser.

**Comment by Benomrans** [comment]
@agmmnn 
Many thanks. Have tried with Dezoomify many times as well with no success, it just gets stuck at the first page for a so long time without returning any errors nor comments.

**Comment by agmmnn** [comment]
Ahh yes you are right, I tried some URLs in Dezoomify, some work, some give SSL error. In this case you can run this repo locally on your machine.

1. Clone the repository
2. Install dependencies and start dev server
```
pnpm install
pnpm dev
```
3. and go http://localhost:3000/

**Comment by agmmnn** [comment]
https://collection.pushkinmuseum.art/entity/OBJECT/145403

dezoomify gives ssl error:
https://dezoomify.ophir.dev/#https://collection.pushkinmuseum.art/entity/OBJECT/145403

locally it is running:
![chrome_c4qGG3t03O](https://github.com/agmmnn/pushkin-downloader/assets/16024979/fcc2ddd9-b8fa-4e32-add6-c98299d23d14)

**Comment by Benomrans** [comment]
Thank you so much. works great.
